Cartelera/Cartelera/Controllers/PeliculasController.cs
using System.Collections.Generic;
using System.Data.Entity.Core.Objects;
using System.Linq;
using System.Web.Mvc;
using Cartelera.DAL;
using Cartelera.Models;
using Cartelera.Models.Peliculas;
using Microsoft.Ajax.Utilities;

namespace Cartelera.Controllers
{
    public class PeliculasController : Controller
    {
        private CarteleraContext db = new CarteleraContext();
        
        // GET: Peliculas
        public ActionResult Index(int? cineId, string str)
        {
                //Combo
                ViewBag.Cines = new SelectList(db.Cines, "Id", "Nombre");


                if (cineId.HasValue && str.IsNullOrWhiteSpace())
                {
                    return View(db.Cines.Find(cineId).GetPeliculas().OrderBy(p => p.Titulo).ToList());
                }

                if (cineId.HasValue && !str.IsNullOrWhiteSpace())
                {
                    str = str.ToLower();
                    return View(db.Cines.Find(cineId).GetPeliculas().Where(p => p.Titulo.ToLower().Contains(str)
                                                        || p is Documental && (p as Documental).Tema.Descripcion.ToLower().Contains(str)
                                                        || p is Comercial && (p as Comercial).Actores.ToLower().Contains(str)).OrderBy(p => p.Titulo).ToList());
                
                }

                if (!str.IsNullOrWhiteSpace())
                {
                    str = str.ToLower();
                    return View(db.Peliculas.Where(p => p.Titulo.ToLower().Contains(str) 
                                                            || p is Documental && (p as Documental).Tema.Descripcion.ToLower().Contains(str) 
                                                            || p is Comercial && (p as Comercial).Actores.ToLower().Contains(str)).OrderBy(p => p.Titulo).ToList());
                }
                return View(db.Peliculas.OrderBy(p => p.Titulo).ToList());

        }
    }
}

Cartelera/Cartelera/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="@Url.Content("~/content/img/favicon.png")" />
    <title>@ViewBag.Title - Pueblo Película</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-fixed-top navbar-inverse">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <span class="navbar-left"><img src="~/Content/img/pueblopelicula.png" width="128" height="50" style="margin-right: 10px"></span>
                @Html.ActionLink("Pueblo Película", "Index", "Peliculas", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="divider-vertical"></li>

                    @if (Url.Action() == "/")
                    {
                        <li class="navbar-form" role="search">
                            @using (Html.BeginForm("Index", "Peliculas", FormMethod.Post))
                            {
                                <div class="input-group">
                                    @Html.DropDownList("Cines", null, "", htmlAttributes: new { Name = "cineId", @class = "form-control" })

                                    <div class="input-group-btn">
                                        <input type="text" id="str" placeholder="Título, Actores o Tema" class="form-control" name="str">
                                        <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                                    </div>
                                </div>
                            }
                        </li>

                    }
                    else
                    {
                        <li>@Html.ActionLink("Películas", "Index", "Peliculas")</li>

                    }


                    @if ((String)Session["admin"] != "codificado")
                    {
                        <li>@Html.ActionLink("Login", "Index", "Login")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Funciones", "Index", "Cines")</li>

                        <li>@Html.ActionLink("Logout", "Logout", "Login")</li>
                    }
                </ul>
            </div>
        </div>
    </div>

    
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)
<script src="@Url.Content("~/Scripts/scripts.js")"></script>
        <div class="container body-content" style="margin-top: 60px">
        @RenderBody()
    </div>

</body>
</html>