Cartelera/Cartelera/Controllers/ComercialesController.cs
using System;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Cartelera.DAL;
using Cartelera.Filters;
using Cartelera.Models;
using Cartelera.Models.Peliculas;

namespace Cartelera.Controllers
{
    public class ComercialesController : Controller
    {
        private CarteleraContext db = new CarteleraContext();

        // GET: Comerciales
        public ActionResult Index()
        {
            return RedirectToAction("Index", "Peliculas", db.Peliculas.ToList());
        }

        // GET: Comerciales/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comercial comercial = (Comercial)db.Peliculas.Find(id);
            if (comercial == null)
            {
                return HttpNotFound();
            }

            ViewBag.Funciones = db.Funciones.Where(f => f.PeliculaId == comercial.Id).ToList().OrderBy(f => f.Horario);
            ViewBag.Cines = db.Cines.ToList();

            return View(comercial);
        }

        [AdminValidator]
        // GET: Comerciales/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Comerciales/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AdminValidator]
        public ActionResult Create([Bind(Include = "Id,Titulo,Duracion,Archivo,Foto,Sinopsis,Actores")] Comercial comercial)
        {
            var fileStream = comercial.Archivo.InputStream;
            var binaryReader = new BinaryReader(fileStream);
            var bytes = binaryReader.ReadBytes((Int32)fileStream.Length);
            var base64String = Convert.ToBase64String(bytes, 0, bytes.Length);

            comercial.Foto = base64String;
            if (ModelState.IsValid)
            {
                db.Peliculas.Add(comercial);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(comercial);
        }

        // GET: Comerciales/Edit/5

        [AdminValidator]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comercial comercial = (Comercial)db.Peliculas.Find(id);
            if (comercial == null)
            {
                return HttpNotFound();
            }
            return View(comercial);
        }

        // POST: Comerciales/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AdminValidator]
        public ActionResult Edit([Bind(Include = "Id,Titulo,Duracion,Foto,Sinopsis,Actores")] Comercial comercial)
        {
            if (ModelState.IsValid)
            {
                db.Entry(comercial).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(comercial);
        }

        // GET: Comerciales/Delete/5

        [AdminValidator]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comercial comercial = (Comercial)db.Peliculas.Find(id);
            if (comercial == null)
            {
                return HttpNotFound();
            }
            return View(comercial);
        }

        // POST: Comerciales/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [AdminValidator]
        public ActionResult DeleteConfirmed(int id)
        {
            Comercial comercial = (Comercial)db.Peliculas.Find(id);
            foreach (Cine cine in db.Cines.ToList())
            {
                if (cine.Contiene(comercial))
                {
                    return Content("<script language='javascript' type='text/javascript'>alert('No se permite eliminar peliculas en cartelera');</script>");

                }
            }
            db.Peliculas.Remove(comercial);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Cartelera/Cartelera/Views/Comerciales/Create.cshtml
@model Cartelera.Models.Peliculas.Comercial

@{
    ViewBag.Title = "Nueva";
}

<h3>@ViewBag.Title</h3>



@using (Html.BeginForm("Create", "Comerciales", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal comercial">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Duracion, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Duracion, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Duracion, "", new { @class = "text-danger" })
        </div>
    </div>

    @Html.HiddenFor(model => model.Foto, new{ Value = "1"})

    <div class="form-group">
        @Html.LabelFor(model => model.Archivo, "Foto (base64)", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.Archivo, null, new { type = "file" })
            @Html.ValidationMessageFor(model => model.Archivo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Sinopsis, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Sinopsis, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Sinopsis, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Actores, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Actores, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Actores, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Crear" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Volver", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Cartelera/Cartelera/Views/Comerciales/Details.cshtml
@using Cartelera.Models
@model Cartelera.Models.Peliculas.Comercial

@{
    ViewBag.Title = Model.Titulo;
}

<div class="row">
    <div class="col-sm-8">
        <dl class="dl-horizontal comercial">
            <dt>
                @Html.DisplayNameFor(model => model.Titulo)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Titulo)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Foto)
            </dt>

            <dd>
                <img src="data:image/jpg;base64,@Html.DisplayFor(model => model.Foto)" width="192" height="256" alt="Poster" />
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Duracion)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Duracion)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Sinopsis)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Sinopsis)
            </dd>

            <dt>
                Tipo
            </dt>

            <dd>
                Comercial
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Actores)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Actores)
            </dd>

        </dl>


        @if ((String)Session["admin"] == "codificado")
        {
            <p>
                @Html.ActionLink("Editar", "Edit", new { id = Model.Id })
            </p>
        }
    </div>

    @if (ViewBag.Funciones != null && ViewBag.Cines != null)
    {
        Cine cineaux = null;
        <div class="col-sm-4">
            <dl class="dl-horizontal comercial">
                <dt style="text-align: center">
                    Funciones
                </dt>

                <dd>
                </dd>
                
                @foreach (Funcion funcion in ViewBag.Funciones)
                {
                        
                    if (cineaux==null || funcion.Sala.Cine.Nombre != cineaux.Nombre)
                    {
                        <dt style="text-align:left">
                            &nbsp; Cine @funcion.Sala.Cine.Nombre
                        </dt>
                        <dd><span>&nbsp;</span></dd>
                    }
                    cineaux = funcion.Sala.Cine;

                    <dd>
                        <span>&nbsp;&bull; Sala @funcion.SalaId &emsp; @funcion.Horario</span>
                    </dd>

                }

            </dl>
        </div>
    }
        </div>

Cartelera/Cartelera/Views/Comerciales/Edit.cshtml
@model Cartelera.Models.Peliculas.Comercial

@{
    ViewBag.Title = "Editar";
}

<h3>@ViewBag.Title</h3>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

@:<div class="form-horizontal comercial">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
        </div>
    </div>

    @Html.HiddenFor(model => model.Duracion)
    
    @Html.HiddenFor(model => model.Foto, new { Value = "1" })

    <div class="form-group">
        @Html.LabelFor(model => model.Foto, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Foto, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Foto, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Sinopsis, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Sinopsis, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Sinopsis, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Actores, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Actores, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Actores, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Guardar" class="btn btn-default" />
        </div>
    </div>
}

@using (Html.BeginForm("Delete", "Comerciales", FormMethod.Post, new { @class = "delete-form" }))
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Borrar" class="btn btn-default" />
        </div>
        @Html.HiddenFor(model => model.Id)
    </div>
}

</div>


<div>
    @Html.ActionLink("Volver", "Index")
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}